version: '3'

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.name=Dozzle
      - flame.url=http://developmentpi.local:8081

  traefik: skal være nginx
    container_name: traefik
    image: traefik:v2.5
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flame: skal være homarr
    image: pawelmalak/flame:multiarch
    container_name: flame
    volumes:
      - ./flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:5005
    environment:
      - PASSWORD=flame
    restart: unless-stopped