version: '3.6'

services:
  flame:
    image: pawelmalak/flame:multiarch
    container_name: flame
    volumes:
      - /home/pi/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:5005
    environment:
      - PASSWORD=flame
    restart: unless-stopped