- hosts: all
  become: true
  tasks:
    - name: Check if FS is expandable
      shell: "raspi-config nonint get_can_expand"
      register: fs_filled
      changed_when: False

    - name: Print if FS is expandable or not
      debug:
        msg: "Filesystem is expandable! [{{ fs_filled.stdout }}]"
      when: fs_filled.stdout == '0'

    - name: Expand Filesystem
      shell: "raspi-config nonint do_expand_rootfs"

https://github.com/giuaig/ansible-raspi-config/blob/master/raspi-config.yml





          - name: Disk usage from command module
            command: df -h
            register: space
          - debug:
                  var: space.stdout_lines