- hosts: all
  become: true
  tasks:
    - name: Check if filesystem is expandable
      ansible.builtin.shell: "raspi-config nonint get_can_expand"
      register: fs_filled
      changed_when: false

    - name: Print if filesystem is expandable or not
      ansible.builtin.debug:
        msg: "Filesystem is expandable! [{{ fs_filled.stdout }}]"
      when: fs_filled.stdout == '0'

    - name: Expand filesystem
      ansible.builtin.shell: "raspi-config nonint do_expand_rootfs"

    - name: Print reboot reminder
      ansible.builtin.debug:
        msg: "Reboot pi after expansion!"
