- hosts: all
  become: true
  tasks:
    - name: Install git
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400
        name: git
        state: present

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Get docker convenience script
      shell: "curl -fsSL https://get.docker.com -o get-docker.sh"

    - name: Execute convenience script
      shell: "sh ./get-docker.sh"

    - name: Check docker service state
      service:
        name: docker
        state: started
        enabled: yes
