- hosts: all
  become: true
  tasks:
    - name: Install nfs-kernel-server
      ansible.builtin.apt:
        update_cache: true
        name: nfs-kernel-server
        state: present

    - name: Create shared directory
      ansible.builtin.file:
        path: /mnt/shared
        state: directory
        owner: pi
        group: pi
        mode: "0775"

    - name: Copy exports file.
      ansible.builtin.template:
        src: ../exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644

    - name: NFS apply change
      ansible.builtin.shell: "exportfs -ra"
