- hosts: all
  become: true
  tasks:
    - name: Reboot
      ansible.builtin.shell: "sleep 1 && shutdown -r now +1"
      async: 1
      poll: 0
      notify:
        - wait-for-reboot

  handlers:
    - name: Wait for reboot
      ansible.builtin.wait_for_connection:
        delay: "5"
        timeout: "300"
