version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
    restart: unless-stopped
    labels:
      - flame.type=application
      - flame.name=Dozzle
      - flame.url=http://developmentpi.local:8081