- name: Update and upgrade apt packages
  hosts: all
  become: true
  vars:
    gotify_url: '{{ lookup("env", "GOTIFY_URL") }}'
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        autoremove: true
      register: apt
      changed_when: false

    - name: Show apt result
      ansible.builtin.debug:
        msg: "{{ apt.stdout_lines }}"

    # - name: Send Gotify Message
    #   ansible.builtin.uri:
    #     url: "{{ gotify_url }}"
    #     method: POST
    #     body_format: json
    #     body:
    #       title: apt upgrade result
    #       message: "{{ apt.stdout }}"
