- name: Download and run dockcheck
  hosts: all
  become: true
  tasks:
    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Download dockcheck script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/mag37/dockcheck/main/dockcheck.sh"
        dest: ~/dockcheck.sh
        mode: u+rwx

    - name: Execute dockcheck
      ansible.builtin.command: "./dockcheck.sh -n -e cron"
      changed_when: false
