- name: Docker prune
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Docker system prune
      ansible.builtin.command: "docker system prune --all --force"
      changed_when: false
