- name: Expand rpi filesystem if possible
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if filesystem is expandable
      ansible.builtin.command: "raspi-config nonint get_can_expand"
      register: fs_filled
      changed_when: false

    - name: Print if filesystem is expandable or not
      ansible.builtin.debug:
        msg: "Filesystem is expandable! [{{ fs_filled.stdout }}]"
      when: fs_filled.stdout == '0'

    - name: Expand filesystem
      ansible.builtin.command: "raspi-config nonint do_expand_rootfs"
      changed_when: false

    - name: Reboot
      ansible.builtin.reboot:
