- name: Download and install docker
  hosts: all
  become: true
  tasks:
    - name: Install git
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400
        name: git
        state: present

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Download docker convenience script
      ansible.builtin.get_url:
        url: "https://get.docker.com"
        dest: ~/get-docker.sh
        mode: u+rwx

    - name: Execute convenience script
      ansible.builtin.command: "sh ./get-docker.sh"
      changed_when: false
