- name: Deploy docker compose
  hosts: all
  become: true
  gather_facts: false
  vars:
    compose_file: "{{ composefile }}"

  tasks:
    - name: Docker compose down
      ansible.builtin.command:
        cmd: "docker compose -f {{ compose_file }} down --remove-orphans"
      changed_when: false

    - name: Docker compose pull
      ansible.builtin.command:
        cmd: "docker compose -f {{ compose_file }} pull"
      changed_when: false

    - name: Docker compose up
      ansible.builtin.command:
        cmd: "docker compose -f {{ compose_file }} up -d"
      changed_when: false
